### ISSUE TITLE
Add integration testing on GKE

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-gke#1]
## Description

This can be done in few ways:

1. Just use cloudtest as in monorepo https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/gke
2. Do steps from https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/gke in the github actions and try to use GKE cli directly in the github actions.

**Comment by edwarnicke** [comment]
@haiodo Do you have opinions here?
