### ISSUE TITLE
Basic Suite doesn't work

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/integration-k8s-gke#443]
## Description
Basic Suite is stuck on Spire deletion. May be related to new Spire configuration with Postgres.

## Run
https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/10258939804/job/28382582003?pr=442

## Logs
[logs_26836013890.zip](https://github.com/user-attachments/files/16517011/logs_26836013890.zip)

**Comment by Ex4amp1e** [comment]
Analysed logs: nothing unexpected
Checked CI: issue has not been reproduced after.

Possible root cause: environment problem with CI agent during specified run.

@denis-tingaikin Looks like issue can be closed since it is not reproducing locally neither on CI after.

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik Can we close the ticket?

**Comment by NikitaSkrynnik** [comment]
Yes, I think it can be closed.
