### ISSUE TITLE
GKE doesn't support IPv6 by default

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-gke#5]
### Description
When we run `TestRunFeatureSuite/TestKernel2Kernel` integration test, we get the next error:
`level=info msg="ping: sendto: Address not available\n" TestRunFeatureSuite/TestKernel2Kernel=stderr`
And the test fails.

This is due to the fact that Google Cloud VPCs do not support IPv6 connectivity.
See: https://cloud.google.com/vpc/docs/vpc?hl=en#networks.

Need to investigate if there is some way to run the test that uses the IPv6 on GKE. 

### Steps to Reproduce
1. Add `TestRunFeatureSuite` to `main_test`
2. See logs when GKE finishes

**Comment by denis-tingaikin** [comment]
@edwarnicke Could you estimate priority for this?

**Comment by edwarnicke** [comment]
@denis-tingaikin What can we do about it?

**Comment by denis-tingaikin** [comment]
@edwarnicke we've discussed this with @glazychev-art and looks like you've fixed the issue by https://github.com/networkservicemesh/sdk-vpp/commit/b7d30d2cc51a8a790001d91af326d84007ef5042 :) 

Currently, @glazychev-art is checking that all working fine on GKE.

**Comment by edwarnicke** [comment]
Woot!

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/sdk-vpp/commit/b7d30d2cc51a8a790001d91af326d84007ef5042
